GET http://localhost:3001/api/users/1
Accept: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsdmFyb2Rlc2FudHMiLCJpZCI6MSwiaWF0IjoxNzIwMzc5OTc1fQ.hfTzTEaeUdu80gRImWkJeJkK2nrkBQBUSHj70TxdTgg

###
